version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-browsers
    steps:
      - checkout
      - run:
        name: Install Dependencies
        command: './scripts/circle-ci-tests.sh'
      - run:
        name: Run Tests 
        command: './scripts/all-tests.sh'
      - run:
        name: Code Coverage
        command: |
        mkdir -p $CIRCLE_TEST_REPORTS/junit
        # Copy the junit results up to be consumed by circleci,
        # but only do this if there actually are results.
        # Note that the greater than zero comparison is doing a
        # string compare, but that should be fine for our purposes here.
        # Do this on each of the containers that were used in
        # the build so that all results are consolidated.
        "if [ $(find reports -type f | wc -l) -gt 0 ] ; then cp -r reports/. $CIRCLE_TEST_REPORTS/junit ; fi":

        # If you have enabled coveralls for your repo, configure your COVERALLS_REPO_TOKEN
        # as an Environment Variable in the Project Settings on CircleCI, and coverage
        # data will automatically be sent to coveralls. See https://coveralls.io/
        # If you have not set up set up coveralls then the following statement will
        # print a message but not affect the pass/fail status of the build.
        # - if [ -z $COVERALLS_REPO_TOKEN ]; then echo "Coveralls token not defined."; else coveralls; fi

        codecov --token=$CODE_COV_TOKEN